from .base import (
    TimestampMixin,
    ResponseModel,
    PaginationParams,
    PaginatedResponse,
    ServiceStatus,
    HealthCheckResponse,
)
from .user import (
    UserRole,
    TravelPreferences,
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    Token,
    TokenData,
)
from .travel import (
    Location,
    Coordinates,
    FlightClass,
    FlightSearchRequest,
    FlightSegment,
    FlightOffer,
    FlightSearchResponse,
    HotelSearchRequest,
    HotelOffer,
    HotelSearchResponse,
    WeatherCondition,
    CurrentWeather,
    WeatherForecast,
    WeatherResponse,
    MessageRole,
    ChatMessage,
    ConversationContext,
    ChatRequest,
    ChatResponse,
)

__all__ = [
    # Base
    "TimestampMixin",
    "ResponseModel",
    "PaginationParams",
    "PaginatedResponse",
    "ServiceStatus",
    "HealthCheckResponse",
    # User
    "UserRole",
    "TravelPreferences",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "Token",
    "TokenData",
    # Travel
    "Location",
    "Coordinates",
    "FlightClass",
    "FlightSearchRequest",
    "FlightSegment",
    "FlightOffer",
    "FlightSearchResponse",
    "HotelSearchRequest",
    "HotelOffer",
    "HotelSearchResponse",
    "WeatherCondition",
    "CurrentWeather",
    "WeatherForecast",
    "WeatherResponse",
    "MessageRole",
    "ChatMessage",
    "ConversationContext",
    "ChatRequest",
    "ChatResponse",
]
